version: '3'
services:

  odm-decisionserverconsole:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:8.11.0.1-amd64
    restart: always
    ports:
    - 9853
    environment:
      - USERS_PASSWORD=odmAdmin
      - HTTPS_PORT=9853
      - DB_TYPE=postgres
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DBNAME}
      - DB_SERVER_NAME=${DBSERVERNAME}
    labels:
    #TODO To Change
      - productName=IBM Operational Decision Manager
      - productId=e32af5770e06427faae142993c691048
      - productVersion=8.11.0
      - metric=free
      - productChargedContainers=decisionserverconsole
    x-aws-pull_credentials:  "${ICRPULLSECRET}" 
    logging:
      driver: "awslogs"
    x-aws-policies:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M

    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9853/res/login.jsf"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisionrunner:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:8.11.0.1-amd64
    restart: always
    labels:
      - productName=IBM Operational Decision Manager - Non Prod
      - productId=e32af5770e06427faae142993c691048
      - productVersion=8.11.0
      - metric=PROCESSOR_VALUE_UNIT
      - productChargedContainers=decisionrunner
    depends_on:
      odm-decisionserverconsole:
        condition: service_healthy    
    environment:
      - HTTPS_PORT=9753
      - DB_TYPE=postgres
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DBNAME}
      - DB_SERVER_NAME=${DBSERVERNAME}
    x-aws-pull_credentials: "${ICRPULLSECRET}" 
    logging:
      driver: "awslogs"
    x-aws-policies:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    ports:
    - 9753
    deploy:

      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9753/DecisionRunner"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisionserverruntime:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:8.11.0.1-amd64
    restart: always
    environment:
      - DECISIONSERVERCONSOLE_NAME=odm-decisionserverconsole
      - HTTPS_PORT=9953
      - DB_TYPE=postgres
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DBNAME}
      - DB_SERVER_NAME=${DBSERVERNAME}
    x-aws-pull_credentials: "${ICRPULLSECRET}" 
    logging:
      driver: "awslogs"
    x-aws-policies:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    depends_on:
      odm-decisionserverconsole:
        condition: service_healthy
    ports:
    - 9953
    labels:
      - productName=IBM Operational Decision Manager
      - productId=b1a07d4dc0364452aa6206bb6584061d
      - productVersion=8.11.0
      - metric=PROCESSOR_VALUE_UNIT
      - productChargedContainers=decisionserverruntime
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9953/DecisionService"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisioncenter:
      image: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:8.11.0.1-amd64
      restart: always
      environment:
      - DECISIONSERVERCONSOLE_PORT=9853
      - DECISIONRUNNER_PORT=9753
      - HTTPS_PORT=9653
      - DECISION_MODEL_DISABLED=true
      - DB_TYPE=postgres
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DBNAME}
      - DB_SERVER_NAME=${DBSERVERNAME}
      x-aws-pull_credentials: "${ICRPULLSECRET}" 
      logging:
        driver: "awslogs"
      x-aws-policies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      ports:
      - 9653
      labels:
        - productName=IBM Operational Decision Manager
        - productId=b1a07d4dc0364452aa6206bb6584061d
        - productVersion=8.11.0
        - metric=PROCESSOR_VALUE_UNIT
        - productChargedContainers=decisioncenter
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 4G
          reservations:
            cpus: '1'
            memory: 1G
      healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:9653/decisioncenter/healthCheck?dontCheckDecisionModel=true"]
        interval: 30s
        timeout: 5s
        retries: 5
        start_period: 50s

